### ISSUE TITLE
Database structure differences Wikka 1.3 vs Wikka 1.2p1 updated to 1.3

### ISSUE THREAD

**Issue by wikkawik** [wikkawik/WikkaWiki#1017]
There are some differences in database structure betweem Wikka 1.2p1 updated to 1.3 and fresh install of Wikka 1.3. These should be resolved before a release. The update procedure of 1.3 installer should be fixed/updated.

'''Table wikka_acls.'''[[BR]]
In 1.2 updated there exists a field that doesn't exist in fresh 1.3:
{{{
`comment_acl` text CHARACTER SET latin1 NOT NULL,
}}}

'''Table wikka_comments.'''[[BR]]
In fresh 1.3 there exists a field that doesn't exist in 1.2 updated:
{{{
`deleted` char(1) COLLATE utf8_unicode_ci DEFAULT NULL,
}}}

'''Table wikka_sessions.'''[[BR]]
In fresh 1.3 a field `sessionid` is of type char(32).[[BR]]
In 1.2 updated a field  `sessionid` is of type varchar(32).[[BR]]
This is caused by a bug in update procedure of 1.3 installer, as in fresh 1.2 it's the same as in fresh 1.3.

'''Table wikka_users.'''[[BR]]
In fresh 1.3 a field `theme` can be NULL.[[BR]]
In 1.2 updated a field  `theme` is NOT NULL.[[BR]]
This is caused by a bug in update procedure of 1.3 installer, as in fresh 1.2 it's the same as in fresh 1.3.

Two more differences are described in #1021 and #1023 — they must be fixed too.

**Comment by bakoontz** [comment]
No longer valid.
