### ISSUE TITLE
UTF-8 related merges (was: 1.3.1 coordination ticket)

### ISSUE THREAD

**Issue by wikkawik** [wikkawik/WikkaWiki#1034]
This ticket is for the preparation of the 1.3.1 release branch, which is branched from 1.3 [1748].  Revisions to be rolled back in this branch are all UTF-8 related:

#431 [1713]-[1715],[1628][[BR]]
#1003 [1701][[BR]]
#990 [1671][[BR]]
#340/#684 [1655][[BR]]

The complete 1.3 branch has been migrated to trunk.  Any working copies of 1.3 you have that contain changes you have made will need to be copied over to a fresh checkout of trunk.

**Comment by bakoontz** [comment]
No longer valid.
