### ISSUE TITLE
Installation fails for MySQL 5.5

### ISSUE THREAD

**Issue by wikkawik** [wikkawik/WikkaWiki#1044]
The installation fails if the user has MySQL 5.5 (or later) installed.

Symptom: All the messages after "Installing Stuff" on the installation page say "FAILED".

Cause: The setup/install.php script creates tables using the TYPE=MyISAM.  However this option is no longer supported in MySQL 5.5.  Use ENGINE=MySQL instead.  (See http://dev.mysql.com/doc/refman/5.5/en/create-table.html).

Workaround: Either hack the code in setup/install.php to replace TYPE= with ENGINE= or use the sql/Wikka_default.sql script instead (which uses ENGINE=).

**Comment by tormodh** [comment]
Installed on PHP 5.5.12 with no problem

**Comment by bakoontz** [comment]
Release 1.3.7 works with MySQL 5.5. Time to move on to a newer version of MySQL...
