### ISSUE TITLE
phrase search doesn't work

### ISSUE THREAD

**Issue by wikkawik** [wikkawik/WikkaWiki#1069]
phrase search doesn't work.  If I go to wikkawiki.org, I see that there is the phrase "things you can do with" on the HomePage.  If I search for "things you can do with" (with the quotes around it) then I find tons of pages which don't include that full phrase.  It seems like the quotes are being ignored.

**Comment by bakoontz** [comment]
This will require either a fix on the branch running wikkawiki.org, or just upgrading wikkawiki.org to the latest version.
