### ISSUE TITLE
Cloning a page shouldn't require write access, just read access

### ISSUE THREAD

**Issue by bakoontz** [wikkawik/WikkaWiki#1180]
Error is generated when attempting to clone a read-only page.  Plus the error message has a spelling error.

**Comment by tormodh** [comment]
Error is not generated when user is attempting to clone a read only page, but when user is attempting to clone into an existing page with read only permissions.

Confirmed spelling mistake: "Sorry! You __don\t__ have write-access to %s"

Should consider better error text + checking if page already exist first.
