### ISSUE TITLE
Existing pages with ws show up as new pages internally

### ISSUE THREAD

**Issue by bakoontz** [wikkawik/WikkaWiki#1186]
If a page is created with ws (e.g., Test Page), internally the parser doesn't recognize the link as pointing to an existing page:

[[Test_Page | test page]] --> shows up as an edit link

(Thanks to MrBarry via #wikka)

**Comment by tormodh** [comment]
Please verify that this is fixed

**Comment by mikeshultz** [comment]
I can confirm similar behavior for simple single-word links as well.

    [[ Example ]]

**Comment by tormodh** [comment]
Thank you @mikeshultz - I'll have another look at it :)

**Comment by bakoontz** [comment]
Test case:

```php
[[Test Page | test page]]

[[Test_Page | test page]]

[[ Test_Page | test page]]

[[ Test Page | test page]]

[[ Test Page ]]

[[ Test_Page ]]
```
