### ISSUE TITLE
clone handler seems to choke on page names containing ws/underscores

### ISSUE THREAD

**Issue by bakoontz** [wikkawik/WikkaWiki#1191]
Sometimes, when cloning a page via the handler, a page containing embedded ws/underscores doesn't get cloned properly, claiming that the target page already exists.  Not always reproducible.

(thanks to MrBarry via #wikka)

**Comment by tormodh** [comment]
Pages with underscore is stored in database with space. Checking for existing page does not look for page with space in name, and will not report duplicate.

Example: cloning into "Test_page" will check if "Test_page" exist, then write to "Test page".

Message could be improved ref #1193
