### ISSUE TITLE
Improve logic and message when cloning a page fails

### ISSUE THREAD

**Issue by tormodh** [wikkawik/WikkaWiki#1193]
Cloning a page first checks if user has read access to the source page.

Then it checks if user is allowed to write the destination page, before checking whether the page exist or not.

A clone onto a page that exist will fail for destination being read-only before it will fail for destination already existing.

**Comment by bakoontz** [comment]
This appears to be fixed, now I'm seeing a "destination exists" error instead of a read-only error.  Thanks, Tormod!
