### ISSUE TITLE
Table not rendering row spans correctly (documentation update needed)

### ISSUE THREAD

**Issue by bakoontz** [wikkawik/WikkaWiki#1206]
This does not work correctly (new column artifacts appear to the right of the table):

```
|=|     |=|Mon|=|Tue|=|Wed|=|Thu|=|Fri|=|
|=|8-9  || ||(y:9)Outreach|| ||(y:9)Outreach|| ||
|=|9-10 || || || || || ||
|=|10-11|| || || || || ||
|=|11-12|| || || || || ||
|=|12-1 || || || || || ||
|=|1-2  || || || || || ||
|=|2-3  ||(y:3)CSCI 102 || ||CSCI 101|| ||CSCI 101||
|=|3-4  || || || || || ||
|=|4-5  || || || || || ||
```

**Comment by tormodh** [comment]
For row and col spans you need to leave a hole in the table markup:

    |=|     |=|Mon|=|Tue|=|Wed|=|Thu|=|Fri|=|
    |=|8-9  || ||(y:9) Outreach|| ||(y:9) Outreach|| ||
    |=|9-10 || || || ||
    |=|10-11|| || || ||
    |=|11-12|| || || ||
    |=|12-1 || || || ||
    |=|1-2  || || || ||
    |=|2-3  ||(y:3) CSCI 102 ||CSCI 101||CSCI 101||
    |=|3-4  || || ||
    |=|4-5  || || ||

**Comment by bakoontz** [comment]
Excellent, thanks!  This space isn't shown in some of the table markup documentation, so I will make the needed changes.
