### ISSUE TITLE
Internal links broken after update to latest version of master branch.

### ISSUE THREAD

**Issue by klenwell** [wikkawik/WikkaWiki#1207]
I just updated to latest master branch. Now internal links like:

    [[AnotherPage Label]]

Render as

    <a class="missingpage" href="/AnotherPage_Label/edit" title="Create this page">AnotherPage Label</a>

Where before it would something like:

    <a href="/AnotherPage">Label</a>

#1186 indicates that this change was deliberate. Is there an upgrade step that is supposed to fix existing links? 

I noticed there were some issues reported when I upgraded, but I ignored them and thought everything went off successfully. Any suggestions for fixing this?

**Comment by bakoontz** [comment]
Links using whitespace delimiters ([[AnotherPage Label]]) were deprecated a
few versions ago.  You'll need to use the pipe symbol as a delimiter:
[[AnotherPage | Label]].

  --Brian

**Comment by klenwell** [comment]
@bakoontz Interesting. Was there a mechanism, an update step perhaps, that fixed existing link (page database records)? 

In my case, at least, this marks a major change in expected behavior. Even though it meant a little bit less flexibility, I've always considered WikkaWiki's simplified link syntax a notable advantage over MediaWiki's.

I'm surprised to hear that this change goes back a few versions, as I have a couple sites that I have been keeping (or least I thought I was) updated where I hadn't noticed it. In this instance, it is true that I was upgrading an older site that hadn't been upgraded for a few years so I suspect there were some bumps during the upgrade process. If there is an upgrade step, I'll re-do my upgrade. If not, I'll look into rolling my own programmatic fix.

**Comment by bakoontz** [comment]
"Old-style" links were deprecated as of 1.3.1:

https://github.com/wikkawik/WikkaWiki/issues/1048

I thought I had posted this up someplace, but perhaps not...an oversight on
my part.  The installer-generated links have all been modified, but you'll
have to fix the broken links. I didn't make that a part of the installer.

**Comment by klenwell** [comment]
For anyone else facing this issue, I created a script to migrate the links. Find the gist here:

[migrateDeprecatedLinks.php](https://gist.github.com/klenwell/ec1a89947ee4f937ca63)

It's mostly quick-and-dirty. If anyone has any suggestions for improving it, please let me know.

**Comment by bakoontz** [comment]
I'll take a look, thanks.  Maybe I can pull it into the installer.

**Comment by klenwell** [comment]
@bakoontz Or if you want to add it to the scripts folder, I can issue a pull request. I followed the example of `convertHTMLEntities.php`.

**Comment by bakoontz** [comment]
That will work!
