### ISSUE TITLE
Website Down?

### ISSUE THREAD

**Issue by kbaltrinic** [wikkawik/WikkaWiki#1209]
Not sure if this is the best place to report this but since I can't find a better place:  The http://docs.wikkawiki.org/ website appears to be down.  I am getting 504 bad gateway errors from nginx.  According to http://downuptime.net/wikkawiki.org.html its not just me and the problem has been going on since yesterday at least.

**Comment by bakoontz** [comment]
Both sites (www and docs) should be back up and running now.  Thanks!
