### ISSUE TITLE
New install: "Parse error: syntax error, unexpected '[' in libs/Wakka.class.php on line 3892"

### ISSUE THREAD

**Issue by baxil** [wikkawik/WikkaWiki#1210]
Tried to upgrade from a previous 1.2 installation, had problems similar/identical to #969.  But then, as part of troubleshooting, deleted wikka directory entirely and attempted a clean install at the same location (just to see if it would bring up the setup page).  All that the fresh bare 1.3.6 gives me is a blank page with:

    Parse error: syntax error, unexpected '[' in /var/www/vhosts/tomorrowlands.org/ttu/libs/Wakka.class.php on line 3892

This is in function LogoutUser().  As such I thought it might be some sort of cookie glitch from the old installation, but Firefox doesn't show any cookies from my website, and nothing changes if I open it in a private browsing window.

It's possible this is a glitch in the server's PHP deployment maybe?  It's a legacy Ubuntu 10.04.4 LTS server running PHP 5.3.2-1ubuntu4.30.  But it doesn't seem to be dropping anything in the error log, and it's displaying it as an actual on-load error rather than as a 500.

**Comment by baxil** [comment]
Per the docs at http://docs.wikkawiki.org/SystemRequirements , I set enable_breadcrumbs => '0' in wikka.php, but no difference.

**Comment by bakoontz** [comment]
You have to run with PHP>5.4.0 for breadcrumbs to work.

**Comment by baxil** [comment]
Yes, that's why I turned it off (the default installation has it on).  It did not change the error.

**Comment by bakoontz** [comment]
I'm not able to reproduce this with the latest master (which will become a new release shortly).  I suspect there might have been a typo that was fixed along the way, but wasn't documented.  If it's still a problem with either the master or the (upcoming) release, feel free to reopen this ticket and I'll take another look at it.
