### ISSUE TITLE
category

### ISSUE THREAD

**Issue by priscille-q** [wikkawik/WikkaWiki#1229]
Hi,

I plan to use WikkaWiki but the documentation is sloppy.
I have created a category that not shown into the category list. and when I try to add it into a subcategory i just got a list of category ...

Thanks,

**Comment by klenwell** [comment]
I've put together a simple demo on my Wikka wiki here:

- [TestCategory](http://klenwell.com/is/TestCategory) (New Category)
  - [TestCategoryPage](http://klenwell.com/is/TestCategoryPage) (Page in TestCategory)
  - [TestSubcategory](http://klenwell.com/is/TestSubcategory) (Subcategory of TestCategory)
    - [TestSubcategoryPage](http://klenwell.com/is/TestSubcategoryPage) (Page in TestSubcategory)

@priscille-q, if you are trying to do something different, perhaps you can clarify.

**Comment by priscille-q** [comment]
that not exactly what i have in my mind, but yeah a sample like that help a lot to figure out how it works.

the documentation is not explicit about for example that the name of the page will be the name of the category. 

so what does {{Category page="something"}}?

**Comment by bakoontz** [comment]
Are you looking at this link?

http://docs.wikkawiki.org/WikiCategory

What part of it doesn't make sense?  If it's not making sense I need to fix it.

**Comment by bakoontz** [comment]
Nothing heard from OP, closing.  Please feel free to reopen if necessary.
