### ISSUE TITLE
Typo on the web site

### ISSUE THREAD

**Issue by Fusl** [wikkawik/WikkaWiki#1231]
I noticed a slightly annoying typo on the [website](http://wikkawiki.org/HomePage)

In the newsflash box you wrote

> **breadcrumbs** must be disabled

However, further down in the code example you wrote (note the missing c in breadcrumbs)

> ('enable_**breadrumbs**' => '0' in wikka.config.php).

Considering there are many people just blindly copy-pasting the text into their favorite editor to change this config value, they will end up not finding it and eventually give up trying to fix it.

According to the [code](https://github.com/wikkawik/WikkaWiki/blob/3f3017c906f0d19794db5c61caab4979ac49e53e/wikka.php#L376), this needs to be changed to **enable_breadcrumbs**.

**Comment by bakoontz** [comment]
Fixed, thanks!
