### ISSUE TITLE
Error with plugin "checklinks"

### ISSUE THREAD

**Issue by chriscase** [wikkawik/WikkaWiki#1237]
When I try to run this I get:

Unknown action ""checklinks""

I installed it in plugins/actions/ and gave it the same permissions as other wiki related files.  I am relatively new to plugins, so maybe I missed something.

Additionally, when I tried to comment on the "checklinks" action dev page, I got an error 500.

See: http://openmindspace.org/CheckLinks

This is the wikkawiki.org page that's broken when I comment:
http://wikkawiki.org/ChecklinksAction/processcomment#comments

**Comment by bakoontz** [comment]
Chris, you should have something like this set up:

plugins/actions/checklinks/checklinks.php

And yes, it does appear that comments on the WW site are broken, thanks for letting me now.  I'll check it out.

**Comment by chriscase** [comment]
That fixed it.  I moved it to "checklinks" under the plugins/actions/ folder and now it works.  Updated the instructions on http://wikkawiki.org/ChecklinksAction to show the path you suggested.
