### ISSUE TITLE
"spam users" after install

### ISSUE THREAD

**Issue by vknews** [wikkawik/WikkaWiki#1254]
After installing wikkawiki, hundreds of users are registering (and create spam pages).
I deleted them, but others come and register.

Then I need to close registration, or password protect them. But I'd like to leave them open...
Is there a way to circumvene this issue?

**Comment by bakoontz** [comment]
Enter these two lines in wikka.config.php:

```
        'UR_validation_modules' => 'URInviteCodeModule',
        'UR_InviteCode_password' => 'my_invite_code',
```

Then distribute the invite code, or make an image of it and past in page (most of the spam accounts are created by bots, not people).
