### ISSUE TITLE
Project still maintained ?

### ISSUE THREAD

**Issue by akerssies** [wikkawik/WikkaWiki#1255]
First of all: thanks for the wikisoftware. It's working great.

Is this project still maintained ? The last release is from a year ago and i was wondering if it will get security updates when needed.

**Comment by bakoontz** [comment]
Yes, it is!  Right now I'm the only active dev on the project, and have gotten a bit behind with the next release.  If there are any immediate security concerns please submit a ticket.  Hopefully a new release is forthcoming soon.

**Comment by farfade** [comment]
Hello,

Thanks for your work !

Do you plan the migration to mysqli ? Debian has just obsoleted php5 and mysql API does not work anymore with PHP7 ;(

**Comment by PieterDeBruijn** [comment]
Same problem here:
"PHP can't find MySQL support but Wikka requires MySQL." and yes MySQL is running just fine. Would be great to see an update!

**Comment by ampersign** [comment]
Check out the [1.4.0-pre](https://github.com/wikkawik/WikkaWiki/tree/1.4.0-pre) branch, it uses PDO instead of the `mysql_` functions. Working well for me on PHP 7.1.8.

**Comment by oemunoz** [comment]
Try the docker:
[https://hub.docker.com/r/oems/wikkawiki/](https://hub.docker.com/r/oems/wikkawiki/)

There are a version for php 5.5 and other for php 7.0.22. 

With the latest fixes. (tnks to @bakoontz)

**Comment by PieterDeBruijn** [comment]
The 1.4.0-pre branch runs fine, thanx!
