### ISSUE TITLE
Modify ACL to allow child pages to use parent's ACL

### ISSUE THREAD

**Issue by wikkawik** [wikkawik/WikkaWiki#139]
Setup the ACL system to allow child pages to either check parent's ACL or, when creating a new page, to copy the parent's ACL to itself, thereby enforcing a protected environment.

Currently, you must implicitly set the ACL on each new page. We have some documents on an intranet site that should only be accesible by administrators. If a user creates a new page and forgets to set the ACL, any valid user can read that page, thereby by-passing our security.

This ticket is also referenced by #217

'''Additional clarification:'''
This ticket actually refers to a couple of different, but related,  concepts:[[BR]]
1. The cloning of ACLs from a source page (addressed in #217).[[BR]]
2. Using the ACL settings of an existing page for the ACLs of a different page.[[BR]]
3. ACL "template" pages that could be used to specify the ACLs for another page.[[BR]]

**Comment by bakoontz** [comment]
Implemented in the clone handler.
