### ISSUE TITLE
Wikka Update notifier

### ISSUE THREAD

**Issue by wikkawik** [wikkawik/WikkaWiki#164]
I'd like to add a simple action to be added to the (default) !WikkaReleaseNotes and/or !WikkaDocumentation page. The action connects to the main Wikka server and checks whether a new version is available. If this is the case a small update box is displayed in the client wiki, otherwise nothing happens.

Issues to take into account are:
 * How to reduce traffic to the wikka website produced by these update checks (keeping in mind that !WikkaReleaseNotes is not among the most frequently viewed pages on client wikis)
 * Where/how to display a notification that a new release is available (adding sth discrete when the Admin is logged-in could also be an option)
 * How to code server-side the handler supposed to announce that new releases are available and what is the most appropriate format (plain text vs. RSS).
 * Make this option configurable, so one can easily switch it off.

**Comment by bakoontz** [comment]
Implemented.
