### ISSUE TITLE
Export of static HTML for offline browsing

### ISSUE THREAD

**Issue by wikkawik** [wikkawik/WikkaWiki#177]
Function for dumping of wiki pages for convenient offline browsing. Maybe as an extension of the usersettings action, because dumps should be user specific, e.g. rights of logged-in user apply for dump. On usersettings then there'd be a button labelled 'Export' which'd activate the compilation of HTML files into a ZIP file, that'd be sent to the user as download.

Naming could occur simply by page name followed by '.html'.  All internal links would be substituted by their '.html' equivalents.

Maybe this feature creates some server load so the admin might want to disable it. A more advanced export function could allow selection of output format, e.g. .CHM, .PDF etc.

=== Related ===
 * #218 - Incorporate html handler to display raw html
 * #190
 * #314
 * #456

**Comment by bakoontz** [comment]
Implemented.
