### ISSUE TITLE
Cleaning up of the handlers/page directory

### ISSUE THREAD

**Issue by wikkawik** [wikkawik/WikkaWiki#188]
Handlers/page has many files in it which don't belong there. We need:

handlers/code/
 * grabcode.php

handlers/comments/
 * addcomment.php
 * delcomment.php

handlers/files/
 * files.xml.php

handlers/mindmap/
 * mindmap.mm.php
 * recentchanges_simple.xml.mm.php
 * recentchanges.xml.mm.php

(alternatively we could think about handlers/xml/ ?)

**Comment by bakoontz** [comment]
No longer relevant.
