### ISSUE TITLE
Immediate change  of "Show comments by default" behavior

### ISSUE THREAD

**Issue by wikkawik** [wikkawik/WikkaWiki#195]
''copied from http://wikkawiki.org/SuggestionBox --NilsLindenberg''

Working on a test installation, I found the user setting "Show comments by default" did not work. Testing it here, I found it doesn't work here, either. --JavaWoman.

It does work.... just not as might be expected. Comment preference is stored for each page as you browse the wiki. So, if you browse a few pages with comments not showing, it remembers this. Then if you update your preferences and return to the same pages, it still remembers that your previous preference was not to see comments on those pages. --JsnX

Right. I see it does work. ;) Somewhat, um, counterintuitive, though. So I guess my suggestion then becomes that when a user configuration is changed, this change should immediately be stored in the user session/cookie so it's active right from that moment (without closing the browser). That would, I think, be more in line with expected behavior. Possible? (I haven't looked at that area of the code yet.) --JavaWoman.

Related issues: #400

**Comment by bakoontz** [comment]
Actually, "Show comments by default" in the UserSettings page doesn't appear to be working...

**Comment by bakoontz** [comment]
Resolved in #195.
