### ISSUE TITLE
New FormOpen() method

### ISSUE THREAD

**Issue by wikkawik** [wikkawik/WikkaWiki#21]
The Wikka core has a FormOpen() method that creates the opening tag for a form. However, it has a number of limitations, such as no way to specify an id and/or class attribute, and not supporting enctype needed for a file upload form. This leads to ugly workarounds and inconsistent (and sometimes invalid) code.

The following replacement for FormOpen() addresses these issues and makes sure the generated code is valid XHTML. It uses a number of new supporting methods that will be more generally useful as well.

=== Ref ===
  * http://wikkawiki.org/AdvancedFormOpen

**Comment by bakoontz** [comment]
Implemented
