### ISSUE TITLE
Unnecessary popup after editing ACLs

### ISSUE THREAD

**Issue by wikkawik** [wikkawik/WikkaWiki#231]
''copied from WikkaBugs --NilsLindenberg''

If you edit the ACL on a page, click "Store ACLs", then edit the ACL and click "Cancel", it still reads "Access control lists updated.", even though the changes were canceled.  This is due to the "Cancel" button causing the browser to navigate backwards, and a javascript popup.  --BarkerJr

**Comment by bakoontz** [comment]
No longer valid.
