### ISSUE TITLE
Sending 404 and 403 headers

### ISSUE THREAD

**Issue by wikkawik** [wikkawik/WikkaWiki#258]
''copied from SuggestionBox --NilsLindenberg''

Right now (1.1.6.0), if a non-existant page is requested, the wiki returns status code 200, which will cause the page to be indexed by search engine spiders.  It'd probably be better to return 404 (not found) or 410 (gone) or include robots exclusion meta tags in the pages that don't exist.  --BarkerJr

Ah, maybe this is why a now non-existent page that I deleted 2 months ago is still getting 50hits or so a day from the porn/vicodin/viagra sites that linked to it (don't ask //me// why...it was a completely inoccuous page)...at least according to the referrers database table. --GmBowen

----
For pages to which the user has no read-access, do you think it might be feasible/interesting to send - along with the //You aren't allowed to read this page// message - a HTTP header like the following:
%%(php) header('HTTP/1.0 403 Forbidden');%% -- DarTar

Oh, and maybe 404 headers for missing pages (which would help prevent SE from spidering links to non existing pages)? -- DarTar

=== Ref ===
 * [http://wikkawiki.org/RobotFriendly]

=== Coordination ticket ===
 * #595

**Comment by mikeshultz** [comment]
+1  

This would be great for crawlers on public pages as well as any kind of non-human scraper.  I was thinking about adding a command to an IRC bot to link to a wiki page if the page exists.  It's much more expensive to parse content of an HTTP GET response instead of issuing a HEAD request.
