### ISSUE TITLE
Skin editor/selector

### ISSUE THREAD

**Issue by wikkawik** [wikkawik/WikkaWiki#29]
Allows users to select/edit/create custom skin.

=== Status ===
coded, some glitches to fix and code cleanup

=== Refs ===
  * http://wikkawiki.org/MySkin
  * http://wikkawiki.org/WikkaSkinOptimization

=== Dependencies ===
Depends on #6

**Comment by bakoontz** [comment]
New theme manager in place.  Old skins will have to be ported over.
