### ISSUE TITLE
Move (default) config into its own class.

### ISSUE THREAD

**Issue by wikkawik** [wikkawik/WikkaWiki#368]
Move from wikka.php the lines 
{{{
$wakkaDefaultConfig = array(...);
}}}
into a file named Config.class.php located in libs/. Default values (and keys) for configuration could be written as class members, then, a function get_object_vars() will transform such class into an array.

What we gain is that each configuration entry can be documented through phpDocumentor blocks.

**Comment by bakoontz** [comment]
Fixed.
