### ISSUE TITLE
Float Right problem on IE7

### ISSUE THREAD

**Issue by wikkawik** [wikkawik/WikkaWiki#419]
As reported by Will Merrell:

I have noticed a problem with a float right box we are using. On IE7 the box spreads 
across the whole page. On Firefox and Opera it works as I would expect.

One solution that sort of fixed the problem was to add a width to the 
floatr css rule. That caused IE7 to render it the same way as the others 
rendered it. The problem with that solution is that then all right 
floats are the same size.

**Comment by bakoontz** [comment]
IE7 no longer relevant...
