### ISSUE TITLE
Installer quits after continuing from first page (usually displaying only a blank page)

### ISSUE THREAD

**Issue by wikkawik** [wikkawik/WikkaWiki#462]
Under some conditions, PHP may have been compiled with MySQL support initially, but for some reason not have access to the shared library that provides MySQL support.  If this occurs, then calls to the MySQL built-in functions (such as mysql_connect()) result in the PHP session unceremoniously aborting, with no error messsages generated.  Testing the return value of these functions is useless, as the function call never completes. 

The ideal solution would be to install calls to mysql_connect in an exception handler, but this is only available in PHP5.  The less-than-ideal solution would be to somehow detect the absence of MySQL shared library support.

Related tickets: #97

**Comment by bakoontz** [comment]
No longer valid.
