### ISSUE TITLE
Encode ACL symbols as constants

### ISSUE THREAD

**Issue by wikkawik** [wikkawik/WikkaWiki#533]
The symbols currently used for ACLs ('*', '+', '!') are used as literal text in several places in the code. It would be better to encode these as constants so the list and their meanings is in a central location and thus more easily maintainable and extensible.

The instructions listed on the page generated by the acls handler should also make use of these constants (and be generated directly as HTML - using the formatter here is unnecessarily "costly", and if it's in HTML it can later be moved to a template).

**Comment by bakoontz** [comment]
HasAccess() only uses the symbols once; any other calls that are using the literals should instead be calling HasAccess() to determine ACL rights.
