### ISSUE TITLE
Cannot upgrade from an older unstable version using the installer

### ISSUE THREAD

**Issue by wikkawik** [wikkawik/WikkaWiki#558]
When I am trying to update from 730 to 735 I won´t pass the page 4 in updating procedure.

{{{
Adding/Updating default page HighScores... FAILED: Default page not found or file not readable (HighScores, HighScores.txt)
[[BR]]
Adding/Updating default page FormattingRules... FAILED: Default page not found or file not readable (FormattingRules, FormattingRules.txt)
[[BR]]
Altering table users : adding field named `challenge'... FAILED
[[BR]]
Rebuilding links table... OK
[[BR]]
Adding fields to comments table to enable threading... FAILED: Already done? OK!
[[BR]]
Adding fields to comments table to enable threading... FAILED: Already done? OK!
[[BR]]
Removing handler field from the pages table... FAILED: Already done? Hmm!
}}}
How do I go on?

/Hans-Eric

**Comment by bakoontz** [comment]
No longer valid.
