### ISSUE TITLE
Case insensitive CamelCase (Link creation, page loading)

### ISSUE THREAD

**Issue by wikkawik** [wikkawik/WikkaWiki#61]
Not really sure if this is a bug, or a feature, or a feature request: the link creator doesn't really care if a link has the "proper" case for the page when it's used in a DB with case insensitive collation (actually, the page loader doesn't care either). As long as it's camelcase (and if you use a forced link, not even that), !HomePage and HomepagE are both valid links pointing to the same page.

The problem is, how to solve that:
 * if you stop recognizing different casings as links to the same page, you might get links to create new pages that are called the same but have different case (very confusing, besides, you'll get into trouble with the DB wanting page tags to be "unique" in the sense "differing in something other than case"). If you don't want to have multiple pages with the same name but different case, you have to handle that separately.
 * Another option would be to ignore malformed links alltogether (probably more trouble than it's worth, users complaining about the engine suddenly stopping to produce links from camelcase words).
 * you could translate malformed Wiki Names into the proper case automatically (provided there's a page)
 * you could detect malformed wiki names when storing/previewing the page, and complain to the user so he fixes it himself
 * do nothing, the current system doesn't seem to have any real trouble with it, and as long as users don't start to deliberately use the wrong case for wikinames it's only a cosmetic deficiency

Related tickets: #191

**Comment by bakoontz** [comment]
Page names are by design case-insensitive.  Also, CamelCase is no longer required, so this ticket is probably invalid.
