### ISSUE TITLE
Strikeout markup incorrectly parsed when adjacent to links

### ISSUE THREAD

**Issue by wikkawik** [wikkawik/WikkaWiki#650]
This markup does not work properly:

{{{
++http://www.google.com++
}}}

The parser interprets the first "+" in the second set of "++" markup chars as part of the URL. 

Workaround is to either separate the markup with spaces:

{{{
++ http://www.google.com ++
}}}

or enclose link in brackets:

{{{
++[[http://www.google.com]]++
}}}

**Comment by bakoontz** [comment]
No longer valid.
