### ISSUE TITLE
WikkaEdit bugs on Firefox @ Mac OS X

### ISSUE THREAD

**Issue by wikkawik** [wikkawik/WikkaWiki#651]
Tested using revision 863, FF 2.0.0.1, Mac OSX 10.3.9 (by BrianKoontz)[[BR]]
Issues:

1. Tab key does not work in editor (jumps to next field). Neither does CTRL-T (jumps to next tab in FF).

2. Hitting the return key in a bulleted list (or numbered list, or commented list) creates the next item, but the cursor immediately jumps to the next (empty) line.

3. When indenting text, text becomes highlighted, which makes no sense because the text is immediately deleted should one attempt to continue with edits.

4. When doing a reverse search, a strange gray box popped up over the edit window (upper right) with two strings: "scroll up" and "log".

**Comment by bakoontz** [comment]
No longer valid.
