### ISSUE TITLE
Edit window doesn't scroll properly in WikkaEdit under IE6

### ISSUE THREAD

**Issue by wikkawik** [wikkawik/WikkaWiki#665]
There is some strange scrolling behavior going on in the edit window under IE6.  It's impossible to scroll to the bottom of the window with the mouse, and the window tries to "jump" to random places as you scroll.  While you can use the arrow keys, highlighting using Shift-<arrow> is sporadic at best, with lines left behind as unhighlighted.

IE info: 6.0.2900.2180.xpsp_sp2_gdr.070227-2254	0

While this is being reported under 1.1.7-docs, the problem almost certainly exists under 1.1.7 as well.

**Comment by bakoontz** [comment]
No longer valid.  Someone will need to test with newer version of IE.
