### ISSUE TITLE
Autogeneration/templatization of .htaccess files

### ISSUE THREAD

**Issue by wikkawik** [wikkawik/WikkaWiki#701]
Now that the setup wizard is modifying the .htaccess and /setup/test/.htaccess files, these need to be templatized or autogenerated in such a way that they are excluded from the "svn checkin" command.  svn does not offer a convenient way to exclude these files (svn:ignore only excludes them from the "svn status" command and a few others).

**Comment by bakoontz** [comment]
This really doesn't appear to be an issue.  .htaccess has been under SCM for a long time with no user complaints.
