### ISSUE TITLE
Please allow underscore in CamelCase

### ISSUE THREAD

**Issue by wikkawik** [wikkawik/WikkaWiki#71]
My problem is the limitation of the page names to CamelCase which seems to be also limitation to letters and numbers. The page names are also used as name in the category system and if you search a category for something it's pretty difficult to do that if you only have CamelCase sentences. What I need is some special character to separate words. As I think it would be difficult to support the space character in the CamelCase words, could you please add support for the underline (_).

**Comment by bakoontz** [comment]
With the change to permit whitespaces, the underscore is now used as a whitespace delimiter in the URL.  So you can create a pagename with underscores, but they will be stored internally with whitespace.
