### ISSUE TITLE
Compatibility with old PHP versions

### ISSUE THREAD

**Issue by wikkawik** [wikkawik/WikkaWiki#718]
Wikka does officially support PHP from 4.1.0. We should check every PHP function and provide compatibility workaround if it is not available as of 4.1.0.

See also #721

To check: checkversion.php (stream_set_timeout).

**Comment by bakoontz** [comment]
As of 1.4.0, the minimum PHP version will be 7.0, with PDO support.  Need to change checks in the code.

**Comment by bakoontz** [comment]
Also see #1096.
