### ISSUE TITLE
Split UserSettings into three different actions:  Login/Logout - Registration - User Settings

### ISSUE THREAD

**Issue by wikkawik** [wikkawik/WikkaWiki#79]
A very popular request from Wikka users: separate login from registration, so as to allow users to run private wikis with no registration form.

=== Refs ===
 * http://wikka.jsnx.com/UserAccountModules
 * http://wikka.jsnx.com/UserRegistration
 * http://wikka.jsnx.com/UserSettingsPanel
 * http://wikka.jsnx.com/RedirectOnLogin
 * http://wikka.jsnx.com/MiKolar
 * http://wikka.jsnx.com/UserSettingsAndPasswords
 * http://wikka.jsnx.com/UserSettingsInfo

== Comments migrated from WIkkaBugs ==
I just started using this program and I love it ! Its exactly what I've been looking for.  However what I want is a Wikki where only the administrator can register new users.  This seems like such an obvious feature that I am amazed I cant figure out how to do it !
What am I missing ? 
--DavidLee

--Sorta Fixed--
Ok I figured this out ... mostly. Feel free to delete this section if its seems obvious to everyone ! (It wasnt to me)
I changed my default ACL for write and comment to "!*" ... but left read as "*".
People can still register themselves but it doesnt do them much good as they cant create pages.
--DavidLee

Hi DavidLee!
No, we don't have an ""{{adduser}}"" yet. If you don't want other people to register, try out the solution from UserRegistration which allows you to stop registration (and you could use phpmyadmin to add users directly to the database). The solution makes it possible to allow registration only with a password, which can be set in the config. See UserRegistration for more details. A division of registration/log-in and usersettings into different actions is planned but won't come in the next release. --NilsLindenberg

== See also ==
#76
#112

**Comment by bakoontz** [comment]
Done.
