### ISSUE TITLE
Numbers as page names

### ISSUE THREAD

**Issue by wikkawik** [wikkawik/WikkaWiki#8]
I'm curious about the Wikka convention that numbers cannot be page names. I'd like to be able to create "date page" (e.g. 2005-02-26) for notes and journaling, so this is a feature I'd definitely suggest.

BTW, doing something along the lines of "journal/2005-02-26" or "journal_2005..." wants to create an external link.

'''Ref'''
* [http://wikka.jsnx.com/SuggestionBox#hn_Numbers_as_page_names Suggestion Box]

**Comment by bakoontz** [comment]
Now allowed, invalid.
