### ISSUE TITLE
Email validation

### ISSUE THREAD

**Issue by wikkawik** [wikkawik/WikkaWiki#80]
Found several issues with how email addresses are validated / accepted / used; outlined on http://wikka.jsnx.com/WikkaAndEmail - and I'm working on solutions. (Email is complicated and there's a whole bunch of standards (RFCs) involved.)

First part of the solutions now in http://wikka.jsnx.com/WikkaEmailToolkit; while the toolkit is still incomplete, what's there now can be used as presented there (no dependencies on later components).

-- JavaWoman

== Related comments migrated from WikkaBugs ==
=== Admin email at installation ===
(Potential) User extremely frustrated when at installation he's entering a real and valid email address and the Installer rejects it with "Email appears incorrect". This is caused by the extremely brain-dead Javascript in the installer that accepts '''nothing but lowercase letters''' to appear before the '@'. To be anywhere like realistic it should be corrected to accept numbers, dots, hyphens and underscores as well.
--JavaWoman (hoping the reporter shows up again so I can help him with a workaround)

The basic problem is that the installer does not use any system routines but instead JavaScript for validation. And the RE it uses for email validation is really, really braindead. Yes, very annoying as I've not seen the user back in #wikka either - we may have lost a user. I  could have given a workaround if only I'd not been sleeping. 
Email library is not quite ready but getting close (needs some restructuring, basically); it will be a class, with several abstract methods so the installer should be able to use it as well (provided it can find the class file). And I'm learning some good tricks working on the sessions module (which might also be useful for Wikka). But the installer needs a major overhaul in any case. Sigh... --JavaWoman

**Comment by bakoontz** [comment]
JS has all been stripped from WW (other than that found in the editors).  This ticket is probably invalid now.
