### ISSUE TITLE
Form IDs need to be regenerated after each form submission

### ISSUE THREAD

**Issue by wikkawik** [wikkawik/WikkaWiki#883]
Currently, the same form ID (unique to each form) is reused during the same session.  For maximum utility, this ID should be regenerated after each form submission.

=== Related tickets ===
#154 Adding Random Tokens for Form Submissions

**Comment by bakoontz** [comment]
At some point in the past we migrated to CSRF tokens.  A single token was set for the entire session.  It's feasible someone could re-submit a form maliciously in the same session if he/she had access to the browser hosting the session.  Now, CSRF tokens are regenerated after each GET/POST session.
