### ISSUE TITLE
Default page ACLs can be modified without page creator's knowledge

### ISSUE THREAD

**Issue by wikkawik** [wikkawik/WikkaWiki#889]
It is possible to set up ACLs for a page that does not exist yet.  In fact, this is the only way to set the ACLs for a new page prior to editing.  The possibility exists that a default set of ACLs can exist for a page prior to its creation and unknown to the creator.  For a wiki that has "read" ACL set to "!_" by default, a registered user could feasibly set read ACL to "_" for any number of pages prior to their creation.

The solution to this problem is to prohibit the creation of page ACLs for pages that do not exist.  But this raises another problem: It would then be impossiblee to create a page and set its ACLs prior to saving the page (in which case the page will be accessible via the default ACLs until the page ACLs are modified).

In addition to the above solution, it would be desirable to also provide the opportunity to set page ACLs upon initial edit of a new page.

**Comment by bakoontz** [comment]
At this point I'm unable to replicate.  I see no way for a user to set ACLs on a page that doesn't yet exist.  If an attempt is made to call the /acls handler on a non-existing page, an ownership error is generated (as it should be).  Closing this one unless someone is able to show that ACLs on non-existing pages can be created by non-admin users.
