### ISSUE TITLE
WikkaInstaller should be a reserved name

### ISSUE THREAD

**Issue by wikkawik** [wikkawik/WikkaWiki#923]
{{{WikkaInstaller}}} should be either automatically created as a user on a default install or marked as reserved (currently a new user can register with {{{WikkaInstaller}}} as a username).

{{{FormatUser()}}} will need to include an option to check whether the author of a revision is {{{WikkaInstaller}}} (and might render it with a specific CSS class to distinguish it from registered and anonymous users).

**Comment by bakoontz** [comment]
No changes made to FormatUser(), not too sure what Dario meant.
