### ISSUE TITLE
Handler() error messages break layout

### ISSUE THREAD

**Issue by wikkawik** [wikkawik/WikkaWiki#925]
The {{{Handler()}}} method, when called with an invalid parameter (e.g. the name of a non-existing component) returns an error message via {{{IncludeBuffered()}}}. 
Error reporting for actions via {{{IncludeBuffered()}}} works fine (as long as a handler is loaded, "show" by default). However when a handler error is found no handler at all is loaded! This breaks the layout as the {{{<div id="content>"}}} div, which is generated by handlers, is not created.

**Comment by bakoontz** [comment]
Cannot recreate.  Possibly fixed in some later release.
