### ISSUE TITLE
Login/logout menulet

### ISSUE THREAD

**Issue by wikkawik** [wikkawik/WikkaWiki#927]
A simple button to be used as a menulet.

=== Todo ===
 * styling (buttons should integrate seamlessly with menus)
 * update menu config files
 * (optional) auto redirect to current page (sending a flag to UserSettings for seamless redirection?)
 * create {{{/logout}}} and {{{/login}}} handlers instead of depending on a default page such as UserSettings

**Comment by bakoontz** [comment]
Implemented.
