### ISSUE TITLE
Installation problem with disabled rewrite on IIS

### ISSUE THREAD

**Issue by wikkawik** [wikkawik/WikkaWiki#940]
I have copied Wikka 1.2 to a sub domain on a web server running PHP 5.2.5 on ISAPI extention on IIS 6.

I opened the Wikka installation page, entered the needed data (did not touched the rewrite options - it was disabled), and successfully completed the configuration.

After going to the home page, there were no styles, no images - just a few menu items and some text to create a homepage - after clicking on it, a message about a failed action was shown (I do not remember exactly which one).

After almost giving up, I found the cause of the problems and the solution:

Problems:
- The installer correctly unchecked the Enable Rewrite (not possible on IIS). But this did not changed the RewriteEngine setting in .htaccess to off. (it stayed on)
- The default Base URI that the installer page set was: "http://mywiki.mywebsite.com/wikka.php?wakka=/?wakka=".

Solution:
- Changing the Base URI to: "http://mywiki.mywebsite.com/wikka.php?wakka="
- Setting the RewriteEngine to off in .htaccess

Note:
If the RewriteEngine is set to off in .htaccess, and than  the installer page is opened (empty config), the default Base URI is correct.

**Comment by bakoontz** [comment]
Nothing heard back from original poster.
