### ISSUE TITLE
getCount() should not return NULL

### ISSUE THREAD

**Issue by wikkawik** [wikkawik/WikkaWiki#948]
{{{getCount()}}} currently returns {{{NULL}}} if no records are found matching the query. However the name implies that it always returns a numeric value (e.g. 0 if no match is found).

We should consider reviewing its use (in actions such as the admin modules) and modifying it as needed (with an eye for backwards-compatibility for potential 3rd party plugins).

**Comment by bakoontz** [comment]
No longer valid.
