### ISSUE TITLE
Better Wakka::GetSafeVar()

### ISSUE THREAD

**Issue by wikkawik** [wikkawik/WikkaWiki#990]
Maybe it can be a possibility to change the `Wakka::GetSafeVar()` to something like this:
{{{
function GetSafeVar($varname, $gpc='get', $default=NULL)
{
    if($gpc == 'get' || $gpc == 'post' || $gpc=='cookie')
    {
        $gpc = strtoupper('_'.$gpc);
        global $$gpc;
        return (isset(${$gpc}[$varname])) ? $this->htmlspecialchars_ent(${$gpc}[$varname]) : $default;
    }
    return $default;
}

}}}

**Comment by bakoontz** [comment]
No longer valid.
